name: Build and Publish

on:
  workflow_dispatch:
    inputs:
      name: 
        description: 'Modpack name'
        default: true
      version:
        description: 'Modpack version'
        required: true

jobs:
  build:
    env:
      NAME: all-the-mods-6
      VERSION: ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build image
        run: |
          docker build . \
            -t curseforge/${NAME}:${VERSION} \
            -t ghcr.io/curseforge-docker/${NAME}:${VERSION} \
            -t curseforge/${NAME}:latest \
            -t ghcr.io/curseforge-docker/${NAME}:latest \
            --build-arg VERSION

      - name: Push to Docker Hub
        run: |
          docker push curseforge/${NAME}:${VERSION}
          docker push curseforge/${NAME}:latest

      - name: Push to Github Container Registry
        run: |
          docker push ghcr.io/curseforge-docker/${NAME}:${VERSION}
          docker push ghcr.io/curseforge-docker/${NAME}:latest
