name: Build and Publish

on:
  workflow_dispatch:
    inputs:
      javaVersion:
        description: 'Java version'
        required: true
        default: 8
      minecraftVersion:
        description: 'Minecraft version'
        required: true
      forgeVersion:
        description: 'Forge version'
        required: true
        default: '14.23.5.2854'
      name:
        description: 'Modpack name'
        required: true
      version:
        description: 'Modpack version'
        required: true
      downloadUrl:
        description: 'Modpack server download url'
        required: true
      projectIdIgnore:
        description: 'Comma-separated list of mod project ids to ignore'
        required: true

jobs:
  build:
    env:
      JAVA_VERSION: ${{ github.event.inputs.javaVersion }}
      MINECRAFT_VERSION: ${{ github.event.inputs.minecraftVersion }}
      FORGE_VERSION: ${{ github.event.inputs.forgeVersion }}
      PACK_NAME: ${{ github.event.inputs.name }}
      PACK_VERSION: ${{ github.event.inputs.version }}
      DOWNLOAD_URL: ${{ github.event.inputs.downloadUrl }}
      PROJECTID_IGNORE: ${{ github.event.inputs.projectIdIgnore }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build image
        run: |
          docker build . \
            -t curseforge/${PACK_NAME}:${PACK_VERSION} \
            -t curseforge/${PACK_NAME}:latest \
            --build-arg JAVA_VERSION \
            --build-arg MINECRAFT_VERSION \
            --build-arg FORGE_VERSION \
            --build-arg PACK_NAME \
            --build-arg PACK_VERSION \
            --build-arg DOWNLOAD_URL \
            --build-arg PROJECTID_IGNORE

      - name: Push to Docker Hub
        run: |
          docker push curseforge/${PACK_NAME}:${PACK_VERSION}
          docker push curseforge/${PACK_NAME}:latest

      - name: Push to Github Container Registry
        run: |
          docker tag curseforge/${PACK_NAME}:${PACK_VERSION} ghcr.io/curseforge-docker/${PACK_NAME}:${PACK_VERSION}
          docker tag curseforge/${PACK_NAME}:${PACK_VERSION} ghcr.io/curseforge-docker/${PACK_NAME}:latest
          docker push ghcr.io/curseforge-docker/${PACK_NAME}:${PACK_VERSION}
          docker push ghcr.io/curseforge-docker/${PACK_NAME}:latest
